<?php

/**
 * @file
 * Install, update and uninstall functions for the system module.
 */

/**
 * Implements hook_install().
 */
function cim_install() {
  // Save a first snapshot.
  // @todo Figure out if there's a way to notify the user when manually enabling
  // the module, but not if enabled in an install profile (that's kinda
  // annoying).
  $ssc = cim_get_controller();
  $snapshot = $ssc->create('Initial snapshot at install time.');
  $ssc->save($snapshot);
}
