<?php

/**
 * @file
 * Configuration interchange and management.
 */

use Drupal\cim\SnapshotController;

/**
 * Implements hook_menu().
 */
function cim_menu() {
  $root = 'admin/config/development/cim';

  $items[$root] = array(
    'title' => 'Configuration Interchange and Management',
    'page callback' => 'cim_admin_list',
    // @todo proper permissions.
    'access arguments' => array('administer site configuration'),
    'file' => 'cim.admin.inc',
  );

  $items[$root . '/list'] = array(
    'title' => 'List',
    'description' => 'List snapshots',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => -1,
    'file' => 'cim.admin.inc',
  );
  $items[$root . '/test'] = array(
    'title' => 'Teststuff',
    'page callback' => 'cim_testing',
    // @todo proper permissions.
    'access arguments' => array('administer site configuration'),
    'type' => MENU_LOCAL_TASK,
    'file' => 'cim.admin.inc',
  );

  $items[$root . '/create'] = array(
    'title' => 'Create snapshot.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('cim_admin_create_snapshot_form'),
    // @todo proper permissions.
    'access arguments' => array('administer site configuration'),
    'type' => MENU_LOCAL_ACTION,
    'file' => 'cim.admin.inc',
  );

  $items[$root . '/snapshot/%cim_snapshot'] = array(
    'title' => 'Snapshot details',
    'page callback' => 'cim_admin_snapshot_view',
    'page arguments' => array(5),
    // @todo proper permissions.
    'access arguments' => array('administer site configuration'),
    'file' => 'cim.admin.inc',
  );

  $items[$root . '/snapshot/%cim_snapshot/details'] = array(
    'title' => 'Details',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => -1,
  );

  $items[$root . '/snapshot/%cim_snapshot/revert'] = array(
    'title' => 'Revert',
    'page callback' => 'cim_admin_snapshot_revert',
    'type' => MENU_LOCAL_TASK,
    'file' => 'cim.admin.inc',
    'access arguments' => array('administer site configuration'),
  );

  return $items;
}

/**
 * Menu loader function.
 */
function cim_snapshot_load($cid) {
  $ssc = new SnapshotController();
  return $ssc->loadCid($cid);
}

/**
 * Get the snapshot controller.
 */
function cim_get_controller() {
  $controller = &drupal_static(__FUNCTION__, NULL);
  if (!isset($controller)) {
    $controller = new SnapshotController();
  }
  return $controller;
}
